### ISSUE TITLE
Wrap each section by <div>

### ISSUE THREAD

**Issue by veznidav** [lucasferreira/react-virtualized-sectionlist#2]
I have sectionHeaderRenderer: 
```javascript
headerRenderer({title, sectionIndex, key, style, isScrolling, isVisible, parent }) {
     return (
            <div key={key} className="list--header" style={style}>
                {title}
            </div>
); }
```
and rowRenderer: 
```javascript
rowRenderer({ item, sectionIndex, rowIndex, key, style, isScrolling, isVisible, parent }) {
    return (
        <div key={key} className="list--item" style={style}>
            <Item key={item.id} data={item} />
        </div>
); }
```
The List is composed as: 
```javascript
<div class="list--header">
    Title 1
</div>
<div class="list--item">
    Item 1 content
</div>
...
```
I would like to have it as follows: 
```javascript
<div class="list--section">
    <div class="list--header">
        Title 1
    </div>
    <div class="list--item">
        Item 1 content
    </div>
</div>
...
```
Can I achieve it somehow?

**Comment by lucasferreira** [comment]
Hi @veznidav 

I have to say that isn't possible by now to achieve that structure, cause all of the "header rows" are just like another list row except for a different class. In a simple way, the header it's a fake row and we are just "cheating" the _react-virtualized_ List about this.

But, why you need to reorganize the List rows structure? It's something to do with CSS for stylizing your list? What do you need to achieve?

**Comment by veznidav** [comment]
Yes, I want to apply CSS on whole sections. I think I will find a workaround how to achieve it, so you can 
 close this issue. Thank you for this cool module.
